name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run tests
        run: ./gradlew test
